export const initial_Tiles = {
    //white
    '1a': true,
    '1b': true,
    '1c': true,
    '1d': true,
    '1e': true,
    '1f': true,
    '1g': true,
    '1h': true,
    '2a': true,
    '2b': true,
    '2c': true,
    '2d': true,
    '2e': true,
    '2f': true,
    '2g': true,
    '2h': true,

    //black
    '7a': true,
    '7b': true,
    '7c': true,
    '7d': true,
    '7e': true,
    '7f': true,
    '7g': true,
    '7h': true,
    '8a': true,
    '8b': true,
    '8c': true,
    '8d': true,
    '8e': true,
    '8f': true,
    '8g': true,
    '8h': true,

    //unoccupied
    '3a': false,
    '3b': false,
    '3c': false,
    '3d': false,
    '3e': false,
    '3f': false,
    '3g': false,
    '3h': false,
    '4a': false,
    '4b': false,
    '4c': false,
    '4d': false,
    '4e': false,
    '4f': false,
    '4g': false,
    '4h': false,

    '5a': false,
    '5b': false,
    '5c': false,
    '5d': false,
    '5e': false,
    '5f': false,
    '5g': false,
    '5h': false,
    '6a': false,
    '6b': false,
    '6c': false,
    '6d': false,
    '6e': false,
    '6f': false,
    '6g': false,
    '6h': false,
}